@RentalService_HostAddress = https://localhost:7023

GET {{RentalService_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{RentalService_HostAddress}}/api/category

###

GET {{RentalService_HostAddress}}/api/category

###

GET {{RentalService_HostAddress}}/api/category

###

GET {{RentalService_HostAddress}}/api/category

###

GET {{RentalService_HostAddress}}/api/category

###

GET {{RentalService_HostAddress}}/api/category

###

GET {{RentalService_HostAddress}}/api/category

###

GET {{RentalService_HostAddress}}/api/category/0

###

GET {{RentalService_HostAddress}}/api/category

###

PUT {{RentalService_HostAddress}}/api/product/1
Content-Type: application/json

{
  //ProductDto
}

###

GET {{RentalService_HostAddress}}/api/productcopy

###
